version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run build"
  test:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run test" 
  deploy:
    docker:
      - image: cimg/node:19.7.0 
    steps:
      - run: docker build -t sachinjondhale278/react-circle-ci:1.0 .
      - run: docker push sachinjondhale278/react-circle-ci:1.0     

workflows:
  ny_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test      